### ISSUE TITLE
实体类继承公共父类，使用selectByExample报错

### ISSUE THREAD

**Issue by mytianya** [mybatis-mapper/mapper#11]
SysDictItemDO集成了BaseEntity，当使用Example方法时会应为找不到BaseEntity上面的类注解时报错
![image](https://user-images.githubusercontent.com/16578015/136944207-dd65b65f-fc73-4ed7-b0ae-59c08777e482.png)
使用BaseEntity上面的delFlag字段查询
![image](https://user-images.githubusercontent.com/16578015/136944260-c3dd2445-bdc0-4ac2-8570-e7e93d55af37.png)
使用报错
![image](https://user-images.githubusercontent.com/16578015/136944305-9421b639-f5f0-488f-b1d4-8efe46b8c067.png)

**Comment by mytianya** [comment]
这种方式有继承BaseEntity的方式是不是不能使用Example了，有其他方式使用了嘛？

**Comment by abel533** [comment]
最新发布的1.0.3版本已解决该问题，不需要对父类进行任何处理。
