### ISSUE TITLE
insert没有回写自动编号

### ISSUE THREAD

**Issue by yongfa365** [mybatis-mapper/mapper#12]
@GeneratedValue(strategy = GenerationType.IDENTITY)
@Column(name = "[ID]", insertable = false, updatable = false)
private Integer ID;

当设置这个就可以了    @Options(useGeneratedKeys = true, keyProperty = "ID")
这个属于元数据，能不能从Entity里自动解析，不然可能每个Mapper都得改下这个

**Comment by abel533** [comment]
sharding-jdbc 示例，有分片，主键各不相同：
https://github.com/mybatis-mapper/mybatis-mapper-example-springboot/tree/shardingsphere
