### ISSUE TITLE
springboot 2.6.1 报错循环引用，不知道是不是哪里配置不对？

### ISSUE THREAD

**Issue by yao00jun** [mybatis-mapper/mapper#24]
2021-12-12 16:53:45 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - [report,40] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  io.mybatis.activerecord.spring.boot.autoconfigure.MapperProviderAutoConfiguration
└──<-──┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

**Comment by abel533** [comment]
最新版本已经解决。
