### ISSUE TITLE
实体类每个属性都要求@Entity.Column是不是有点多余

### ISSUE THREAD

**Issue by languanghao** [mybatis-mapper/mapper#25]
通常Domain对应的就是数据库表，属性跟字段就是一一对应关系，顶多名字可能不同，建议增加一个配置，默认所有属性都是数据库表字段，可以通过@Transient进行排除

**Comment by yuan50697105** [comment]
一般正常使用字段的小驼峰是对应数据表中间带有下划线的写法，但是你这个为什么不是这么设计的，这样每个都要加注解去翻译字段

**Comment by abel533** [comment]
会考虑这种基于默认的配置，减少注解。

同时推荐用代码生成器生成。

**Comment by abel533** [comment]
针对 jpa 包做了修改，支持不带任何注解的实体类。

**Comment by crazyweeds** [comment]
希望修改一下说明文档（必须添加 @Entity.Column），因为这个，我来提issue，习惯性搜索了下，幸好已经优化了。但如果没有优化的话，我相信我依然会用tk，毕竟太麻烦了，吓退了我。

**Comment by afk6** [comment]
好奇这个针对默认配置的优化是什么时候改的..  我用的1.2.2, 目前看起来生成的SQL
> SELECT  FROM user

我没有添加`@Entity.Column`, 只加了`@Entity.Table`.

**Comment by LSL1618** [comment]
> 希望修改一下说明文档（必须添加 @Entity.Column），因为这个，我来提issue，习惯性搜索了下，幸好已经优化了。但如果没有优化的话，我相信我依然会用tk，毕竟太麻烦了，吓退了我。

现在的文档还是这样说明的：
`实体类上 必须添加 @Entity.Table 注解指定实体类对应的表名，建议明确指定表名，不提供表名的时候，使用类名作为表名。 所有属于表中列的字段，必须添加 @Entity.Column 注解，不指定列名时，使用字段名（不做任何转换），通过 id=true 可以标记字段为主键。`
JPA注解毕竟用的太熟太广泛了。
