### ISSUE TITLE
遇到一个奇怪的问题，启动项目之后，第一次查询，返回的是null

### ISSUE THREAD

**Issue by yao00jun** [mybatis-mapper/mapper#27]
启动项目之后，第一次查询，会遇到如下问题，再次查询就不会了。好奇怪
单个查询 mapper.selectOne(T)   返回的实体 里面的部分属性  是null 
多个查询 mapper.selectList（null) 返回的 集合 List 的size 是20 但是 List 里面全是null
不知道是什么原因，使用版本是 1.0.3
查看打印的SQL是正常的SQL直接去数据库查也是正常的结果

**Comment by yao00jun** [comment]
发现去掉 autoResultMap 就正常了

**Comment by abel533** [comment]
有 `autoResultMap` 时，查询SQL字段应该没有别名，去掉后会有别名。

**Comment by abel533** [comment]
最新版本测试没有发现问题。
