### ISSUE TITLE
如何实现根据自定义策略自动生成主键

### ISSUE THREAD

**Issue by PigPigMan1024** [mybatis-mapper/mapper#28]
如何实现 类似 tk.mybatis 中的 `@KeySql(genId = SnowflakeGenId.class)` 一样的功能

**Comment by abel533** [comment]
先在service层封装吧

**Comment by kk-fan** [comment]
同求tk.mybatis 中的 @KeySql 使用 @KeySql(genId = SnowflakeGenId.class) 就可以不配置配置 sharding 的 key-generator 属性了 还有一个需求公司表有业务主键和逻辑主键 之前在使用通用mapper的时候只需要在业务主键上添加 @KeySql(genId = UUIDGenId.class) 很方便

**Comment by abel533** [comment]
后续看看能不能给mybatis提交个可以自定义主键生成器的方案。

**Comment by abel533** [comment]
provider中已经实现，将会发布新版本
