### ISSUE TITLE
继承BaseMapper时，如果是联合主键泛型参数应该如何填写？

### ISSUE THREAD

**Issue by hzw133** [mybatis-mapper/mapper#35]
如题，我有一张表，其中的三个字段组成主键，并且这三个字段不是同一类型的，这时候我继承`BaseMapper<T, I extends Serializable>`，请问泛型参数中的主键类型要怎么填写

**Comment by ydq** [comment]
没记错的话 应该是对象本身 `userMapper extends BaseMapper<User,User>`

然后 如果根据主键查询，也是用对象本身设置多个主键字段的值即可，希望没误导你，可以测试一下
