### ISSUE TITLE
tk-mapper中的IDynamicTableName，动态表名能支持下吗？或者有什么好的办法实现？

### ISSUE THREAD

**Issue by marsal1212** [mybatis-mapper/mapper#48]

**Comment by marsal1212** [comment]
自己拉下来代码实现了一下，通过entity.table中的prop加入了两个属性配置
dynamicTable 用来做动态表名 user${suffix}xx，suffix为entity中的自定义字段
dynamicTable.return 用来处理查询中是否返回该字段
example中加入了dynamicTableVar，自定义动态表名中的变量。
不支持单个简单类型参数的方法，如：selectByPrimaryKey / deleteByPrimaryKey..

![image](https://user-images.githubusercontent.com/20449902/180115087-f7915006-9823-4ea5-857a-10ded378b096.png)
![image](https://user-images.githubusercontent.com/20449902/180114255-fd863f6e-6c7a-4663-933d-130120974a9f.png)
![image](https://user-images.githubusercontent.com/20449902/180114316-8fb8eaaf-713c-4c58-b940-f974879a8b80.png)
![image](https://user-images.githubusercontent.com/20449902/180114383-1dfb3f5c-c0f0-4c46-8150-84db2e95879b.png)
![image](https://user-images.githubusercontent.com/20449902/180114458-322ec949-0823-49ff-8b82-ebf612d12b24.png)
![image](https://user-images.githubusercontent.com/20449902/180115342-da21fdb7-e8b9-496a-85af-c73c0f8ba38c.png)

用法：
![image](https://user-images.githubusercontent.com/20449902/180115153-9a637759-241f-44ec-abbe-a47733810d5d.png)
![image](https://user-images.githubusercontent.com/20449902/180115195-737eab19-c796-45bc-a3d8-0f520687733e.png)
![image](https://user-images.githubusercontent.com/20449902/180115238-c39699bb-4f86-4d53-8f3c-45fa5657843e.png)
![image](https://user-images.githubusercontent.com/20449902/180115260-9dd946fe-d760-41ae-bdd4-eafdf2d97ca1.png)

**Comment by abel533** [comment]
目前的实现方案如下：
```java
@Test
public void testSelectByPrimaryKey() {
  SqlSession sqlSession = getSqlSession();
  try {
    EntityMapper<User, Long> entityMapper = sqlSession.getMapper(UserMapper.class);
    Optional<User> user = DynamicTableName.hint("user_2", () -> entityMapper.selectByPrimaryKey(1L));
    Assert.assertTrue(user.isPresent());
  } finally {
    sqlSession.close();
  }
}
```
目前通过调用静态方法设置，优点是所有方法都能直接支持，不需要给某些实体方法设置额外的表名。

上述 selectByPrimaryKey 对应的方法如下：
```xml
<script>
SELECT id,name AS userName,sex FROM ${@io.mybatis.extra.dynamic.tablename.DynamicTableName@table('user')}
<where>
id = #{id}
</where> 
</script>
```

可以先针对当前实现反馈一下。

**Comment by marsal1212** [comment]
我这边直接上了sharding-jdbc的hint分表。强制指定，和上面的方法很类似。

谈谈上面这种做法的感受：代码写起来太割裂了。
正常情况下，需要写sql的地方，肯定会定义好动态后缀参数。需要动态表名的，也只是mapper内的一些方法。
