### ISSUE TITLE
升级2.0.0之后，如何排除实体类 继承的父类的 映射

### ISSUE THREAD

**Issue by yao00jun** [mybatis-mapper/mapper#56]
我有一个实体类User，继承的父类BaseVO，例如，User表结构 有字段 A 、B  实体类User有属性A、B 父类BaseVO  有属性C，D，
升级2.0.0之后，会报错说 数据库User表找不到对应的属性C和D。 
 请问，如何排除 父类的 映射？
以前1.2.2版本 没有问题。

**Comment by yao00jun** [comment]
找到个 @Entity.Transient 注解 ，但是只能排除字段，不能排除整个父类。。。因为父类是公司框架封装好的，无法修改。

**Comment by abel533** [comment]
继承排除字段是个问题，先别升级。。等出个方案兼容这种情况。

你有好的想法吗？

**Comment by drtrang** [comment]
抛出一种方式，大家共同讨论。

方案：实体类中主动声明表中的字段，而不是排除，再通过多种形式扩展生效范围
举例：
1. @Column 可声明在 field 上，适用于大多数场景
2. @Column 可声明在 getter/setter 方法上，适用于继承父类的场景，可重写 getter/setter 实现添加 @Column 注解
3. @Columns 可声明在 class 上，适用于全部场景，

该 idea 来源于 Jackson，分别对应 @JsonProperty、@JsonProperties

**Comment by abel533** [comment]
@drtrang 这是最常见的方式，目前 @ydq 可能在尝试双向绑定，读取表结构和实体字段进行绑定。

如果没有更好的方式实现，会按照 @drtrang 这里提供的方式实现。

**Comment by abel533** [comment]
注解增加3个属性用于排除字段：

https://github.com/mybatis-mapper/provider/commit/6e46c24e0d96b56502ff96fc8230a760e8027328

```java
@Entity.Table(value = "user",
    excludeSuperClasses = Role.class,
    excludeFieldTypes = User1.class,
    excludeFields = "age")
public class UserExclude extends Role {
  @Entity.Column(id = true, useGeneratedKeys = true)
  private Long   id;
  @Entity.Column("name")
  private String username;

  private User1 user1;

  private int age;

```

**Comment by gonglb** [comment]
感觉以下的不是特别需要，反而会增加复杂度
excludeFieldTypes = User1.class,
excludeFields = "age"
可以用@Entity.Transient代替
