### ISSUE TITLE
睿Rui代码生成器的代码生成问题

### ISSUE THREAD

**Issue by index-cat** [mybatis-mapper/mapper#60]
1.生成的实体类，字段希望能加上注释，目前字段上只有注解；
如果把实体类放在通用API包中，就需要额外添加注释
2.生成的Mapper类，没有引入实体类，需要额外编辑引入实体类
3.使用model-lombok.java生成的实体类，生成的代码不正确

**Comment by abel533** [comment]
睿代码生成器使用的模板，你这里提到的所有问题都可以通过配置模板实现。
