### ISSUE TITLE
是否考虑将分页逻辑融合进来？

### ISSUE THREAD

**Issue by Shiyajian** [mybatis-mapper/mapper#61]
分页是个基本需求。同时引入mapper + pagehelper时候需要两个依赖，两个插件的兼容，版本依赖差异是一系列的问题。是否可以考虑，像mp一样，集成分页的功能，方便维护、使用。

**Comment by abel533** [comment]
打包时用shade把pagehelper包含进来？

**Comment by dfjfj** [comment]
这两个项目应该没有交集吧? 似乎没必要整合进来, 不然还限制了别人单独手写的分页插件.
