### ISSUE TITLE
希望Example能加上excludeColumns

### ISSUE THREAD

**Issue by huzhenquan** [mybatis-mapper/mapper#63]
从tkMapper转过来的，Example的excludeColumns是真的好用，希望能加上

**Comment by abel533** [comment]
加。

**Comment by huzhenquan** [comment]
谢谢大佬

**Comment by huzhenquan** [comment]
> 加。

谢谢大佬

**Comment by abel533** [comment]
```java
//设置查询id
example.selectColumns(User::getId);
//设置排除id，会覆盖前面的配置
example.excludeColumns(User::getId);
```
按照原来的接口，`selectColumns` 可以多次指定，会追加到一起，此次修改后，每次调用都会覆盖，不会追加。

调用排除时也会覆盖。如下面几个图：

![image](https://user-images.githubusercontent.com/1787798/204116791-91992999-8e9c-452a-9bcc-2057451a4b14.png)
![image](https://user-images.githubusercontent.com/1787798/204116796-947755b5-034b-426e-b211-54a7a41dd521.png)
![image](https://user-images.githubusercontent.com/1787798/204116804-7d9c892c-d4b6-4a2d-a5fc-61d134a10a18.png)
