### ISSUE TITLE
提问：如何使用Table内的resultMap

### ISSUE THREAD

**Issue by wxk6b1203** [mybatis-mapper/mapper#64]
`@Entity.Table`内有一个resultMap字段，我看了代码是直接通mybatis的。对这一块并不了解，不知道这块该如何使用？

**Comment by abel533** [comment]
会直接在内存创建和 xml resultMap 类似的数据结构，使用resultMap后，查询列不需要通过 `as` 设置别名，查询也能支持 typeHandler。

**Comment by wxk6b1203** [comment]
> 会直接在内存创建和 xml resultMap 类似的数据结构，使用resultMap后，查询列不需要通过 `as` 设置别名，查询也能支持 typeHandler。

明白了，我去看一下mybatis内这个字段怎么用的，感谢感谢
