### ISSUE TITLE
主键自定义

### ISSUE THREAD

**Issue by ChengSense** [mybatis-mapper/mapper#69]
现在主键只能定义为id，希望可以自定义

**Comment by abel533** [comment]
支持自定义。。如果有统一的，可以在基类重新通过 `@Options` 配置，如果各不相同，需要每个实体中覆盖默认定义。

**Comment by abel533** [comment]
后续会考虑支持占位符，自动读取标记的主键字段名。

**Comment by abel533** [comment]
在 provider 中已经实现。
