### ISSUE TITLE
insertSelective()后无法获取id

### ISSUE THREAD

**Issue by lengmianshi** [mybatis-mapper/mapper#71]
1.2.2版本，数据插入后无法获取主键，请问是什么原因？

**Comment by lengmianshi** [comment]
![image](https://user-images.githubusercontent.com/18379086/202339758-0d1c2dc3-4937-4fb7-a05c-2f09358282c1.png)

**Comment by abel533** [comment]
方法默认没有配置主键回写：
```java
/**
   * 保存实体中不为空的字段
   *
   * @param entity 实体类
   * @return 1成功，0失败
   */
  @Lang(Caching.class)
  @InsertProvider(type = EntityProvider.class, method = "insertSelective")
  int insertSelective(T entity);
```

如果你是自增主键，需要自己配置，参考文档：https://mapper.mybatis.io/docs/2.mybatis-mapper.html#_2-2-%E9%87%8D%E5%86%99%E7%BB%A7%E6%89%BF%E6%8E%A5%E5%8F%A3%E7%9A%84%E5%AE%9A%E4%B9%89

```java
/**
 * 保存实体，默认主键自增，并且名称为 id
 * <p>
 * 这个方法是个示例，你可以在自己的接口中使用相同的方式覆盖父接口中的配置
 *
 * @param entity 实体类
 * @return 1成功，0失败
 */
@Override
@Lang(Caching.class)
@Options(useGeneratedKeys = true, keyProperty = "id")
@InsertProvider(type = EntityProvider.class, method = "insert")
int insert(T entity);
```

暂时必须通过 `keyProperty = "id"` 配置，如果实体主键各不相同，需要在各个实体Mapper中覆盖该接口定义。

**Comment by lengmianshi** [comment]
感谢大大，自定义insertSelective()方法，加上@Options(useGeneratedKeys = true, keyProperty = "id")注解后成功拿到id了！
