### ISSUE TITLE
未知错误，无法扫描mapper

### ISSUE THREAD

**Issue by x-j-j** [mybatis-mapper/mapper#72]
以前用tk时加上Mapper注解可以扫描到的，为啥这个显示无法注册bean呢，我使用的h2数据库
<img width="1241" alt="截屏2022-12-11 11 28 10" src="https://user-images.githubusercontent.com/71647398/206884927-67f319dd-9dd1-4347-adf0-e6d0bfdf9dba.png">
<img width="306" alt="截屏2022-12-11 11 30 31" src="https://user-images.githubusercontent.com/71647398/206884981-3547c3f9-f933-4e94-8980-d0a94b687293.png">

<img width="697" alt="截屏2022-12-11 11 28 52" src="https://user-images.githubusercontent.com/71647398/206884934-bd6afd06-e193-4ba4-87fb-8f8f34bc6610.png">
<img width="572" alt="截屏2022-12-11 11 29 01" src="https://user-images.githubusercontent.com/71647398/206884939-4254f1ef-f35d-40c9-8795-f8b63e3fa2a8.png">

```
        <dependency>
            <groupId>io.mybatis</groupId>
            <artifactId>mybatis-mapper</artifactId>
            <version>2.0.0</version>
        </dependency>
```

**Comment by abel533** [comment]
完全按照mybatis用法就能使用，如果有问题，先试试mybatis本身有没有问题。

**Comment by x-j-j** [comment]
好嘞，我试下，谢谢老大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月11日(周日) 下午3:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mybatis-mapper/mapper] 未知错误，无法扫描mapper (Issue #72)




 
完全按照mybatis用法就能使用，如果有问题，先试试mybatis本身有没有问题。
