### ISSUE TITLE
Example `andIn` 比较集合为空集合时的情况

### ISSUE THREAD

**Issue by tianyu94** [mybatis-mapper/mapper#75]
如果 `andIn` 比较值为 empty，SQL 会异常

例如

```
AND f1 IN ()
```

这种是否可以考虑通过配置方式，或者默认将 empty 的集合（Collection）忽略其查询条件？

**Comment by abel533** [comment]
ExampleWrapper中有类似下面的方法 https://github.com/mybatis-mapper/mapper/blob/fca2ce29f7492aa0bdde9319361aa8cc33962b86/mapper/src/main/java/io/mybatis/mapper/example/ExampleWrapper.java#L496：
```java
@SuppressWarnings("rawtypes")
  public ExampleWrapper<T, I> in(boolean useCondition, Fn<T, Object> fn, Iterable values) {
    return useCondition ? in(fn, values) : this;
  }
```
