### ISSUE TITLE
怎么使用这个版本调用存储过程啊？

### ISSUE THREAD

**Issue by terry8yu** [mybatis-mapper/mapper#76]
哪里有demo可以看如何调用存储过程的？
多谢啦！

**Comment by abel533** [comment]
存储过程就是Mybatis本身的功能。

https://blog.csdn.net/isea533/article/details/76358365
https://blog.csdn.net/isea533/article/details/77148552
https://blog.csdn.net/isea533/article/details/77592456

**Comment by terry8yu** [comment]
还有个问题想问一下：之前有MapperTemplate可以获取实力类对应的表名称，现在这个版本是如何获取实体类对应的表名的？

**Comment by abel533** [comment]
io.mybatis.provider.EntityInfoMapper 这个接口中有方法可以获取。

或者用下面的方法获取：

https://github.com/mybatis-mapper/provider/blob/12d1ca2dc5e1f9019da7c7f0552c5d938865e5e8/src/main/java/io/mybatis/provider/EntityFactory.java#LL58C32-L58C32
