### ISSUE TITLE
实体类中某个字段不加注解新增修改时依然会报该字段不存在

### ISSUE THREAD

**Issue by MarkusMxd** [mybatis-mapper/mapper#91]
之前我们可以用@transient注解来声明，现在我想在实体类中添加个别非表中字段，查看文档说什么都不加就可以，但是依然报错，尝试将该字段上面加注解@Entity.Column(selectable=false,updatable = false,insertable = false)，莫非只能这样？？看是否需要调整

**Comment by abel533** [comment]
使用 `@Entity.Transient` 可以排除，添加jpa模块的情况下也可以使用JPA的注解。

**Comment by abel533** [comment]
最新文档： https://mapper.mybatis.io/docs/v2.x/1.getting-started.html
