### ISSUE TITLE
当xml里定义的接口和BaseMapper里的重合,会报错

### ISSUE THREAD

**Issue by zzz1255** [mybatis-mapper/mapper#98]
使用版本:mapper:2.2.1
一个现有使用mybatis的项目切换到mapper
当mapper.xml里面已经定义某个方法,比如insert,这种情况下使用mapper启动会报错提示
Mapped Statements collection already contains value for xx.xx.insert
是不是以xml里存在的为准去覆盖基础mapper里的,而不是报错

**Comment by abel533** [comment]
mybatis自己的机制，xml和注解在同一个命名空间不能重复。
